# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-09 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=250)),
                ('book_sub_title', models.CharField(max_length=250)),
                ('book_description', models.TextField(blank=True, null=True)),
                ('book_ISBN', models.CharField(max_length=250)),
                ('book_pages', models.CharField(max_length=250)),
                ('book_year', models.CharField(max_length=250)),
                ('book_cover', models.FileField(max_length=250, upload_to='books/cover/')),
                ('book_pdf', models.FileField(max_length=250, upload_to='books/pdf/')),
                ('book_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('category_title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('publisher_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Category'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Publisher'),
        ),
    ]
